# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /#bio
    weight: 10
  #- name: Talks
  #  url: /#talks
  #  weight: 12
  #- name: News
  #  url: /#news
  #  weight: 13
  - name: Experience
    url: experience/
    weight: 20
  - name: Skills
    url: skills/
    weight: 25
  - name: Software
    url: projects/
    weight: 27
  #- name: Teaching
  #  url: teaching/
  #  weight: 40
  - name: Publications
    url: papers/
    weight: 40
  - name: Awards
    url: awards/
    weight: 30